FROM python:3.7-alpine

WORKDIR /app

RUN pip install Flask

COPY hello.py .

#The next line is no more required, as
#we are directly work with hello.py
#COPY start-app.sh .

env FLASK_APP "hello"
env FLASK_ENV "development"
env FLASK_RUN_HOST "0.0.0.0"

CMD ["flask","run"]
