FROM python:3.7-alpine

COPY start-app.sh /data/

RUN echo "One more line" >> /data/start-app.sh

#Comment to update in hello.py
VOLUME /data

COPY hello.py /data/

RUN echo "One more line" >> /data/hello.py

RUN more /data/start-app.sh

RUN more /data/hello.py
